package com.bravo.view;
import com.bravo.utils.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.SpringLayout;
public class ProfileDialog extends javax.swing.JDialog{
	private static final long serialVersionUID = 5427903396379849829L;
	private MainWindow mainWindow;
    JTextField username;
    JPasswordField password;
    JPasswordField confirmPassword;
    JTextField email;
    JTextField confirmEmail;
    
    public ProfileDialog (MainWindow mw,java.awt.Frame parent, boolean modal ){
    	super(parent, modal);
        mainWindow = mw;
        initComponents();
        initMyComponents();
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        this.getRootPane().registerKeyboardAction(closeActionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
    }
    
    ActionListener closeActionListener = new ActionListener(){
    	@Override
    	public void actionPerformed (ActionEvent actionEvent){
    		dispose();
    		
    	}
    };
    public void initMyComponents(){
    	this.setTitle("Profile");
    	
    	JPanel ProfilePanel = new JPanel ();
    	username=new JTextField();
    	password = new JPasswordField();
    	confirmPassword = new JPasswordField();
    	email= new JTextField();
    	JButton UpdateProfile = new JButton("Update Profile");
    	//UpdateProfile.addActionListener(UpdateProfileAL);
    	
    	
    	ProfilePanel.add(new JLabel("Username: "));
    	ProfilePanel.add(username);
    	ProfilePanel.add(new JLabel("Existing password: "));
    	ProfilePanel.add(password);
    	ProfilePanel.add(new JLabel("New password: "));
    	ProfilePanel.add(new JLabel("Email"));
    	ProfilePanel.add(email);
    	SpringUtilities.makeCompactGrid(ProfilePanel, 5, 2, 10, 10, 10, 10);
        this.add(ProfilePanel);
        
        JPanel ProfileButton = new JPanel();
        ProfileButton.add(UpdateProfile);
        this.add(ProfileButton);
        
        
    	
    }
   /* ActionListener UpdateProfileAL = new ActionListener(){
    	@Override
    	public void actionPerformed (ActionEvent actionEvent){
    		
    	}
    
    
    	
    
    };
	*/

    public void update() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setName("Form"); // NOI18N
    getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

    pack();
}// </editor-fold>//GEN-END:initComponents
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
}
